### ISSUE TITLE
Body does not seem properly formated and cors error

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/functions-js#12]
# Bug report

The documentation shows calling a function as:
```
const { data: user, error } = await supabase.functions.invoke('hello', {
  responseType: 'text',
  body: { foo: 'bar' }
})
```
The function.js code has
```
const response = await this.fetch(`${this.url}/${functionName}`, {
        method: 'POST',
        headers: Object.assign({}, this.headers, headers),
        body,
      })
```
I would think at a minimum body should be body:body.   
Very strange results occur, but basically content length is string length if {body:'string'} is used in call. 
If an object is used {body:{k:'v'}, length is always 15  probably an error message for invalid object or something...

Not sure if it is related.  But all calls generate cors errors:

![image](https://user-images.githubusercontent.com/54564956/161358245-3ea3dc32-ff5d-4920-9690-647a3b7c4868.png)

## To Reproduce

Follow the instructions for functions invoke in api reference.

## Expected behavior

Body should be formatted correctly and no cors error (if not related)

## System information

Latest supabase.js

**Comment by GaryAustin1** [comment]
It appears to use functions.js Edge Functions need more than the sample code shown so far.
I had to add allow headers to the return..
https://github.com/supabase/supabase/issues/6267

**Comment by GaryAustin1** [comment]
Finally got it all to work:
Seems body: is optional in fetch?  BUT the documentation shows passing in an object for body.  When I passed in a json string:
body:'{"name":"gary"}'   The body gets passed correctly.

Also for the browser to work with function.js  I had to deal with an OPTION request and the POST request, both with allow headers like such:

```
import { serve } from "https://deno.land/std@0.131.0/http/server.ts";

console.log("Hello from Functions!");

serve(async (req) => {
        console.log(req.method)
        if (req.method === 'OPTIONS') {
            return new Response(
                'ok',
                {
                    headers: {
                        "Access-Control-Allow-Origin": "*",
                        "Access-Control-Allow-Methods": "POST",
                        "Access-Control-Expose-Headers": "Content-Length, X-JSON",
                        "Access-Control-Allow-Headers": "apikey,X-Client-Info, Content-Type, Authorization, Accept, Accept-Language, X-Authorization",
                    }
                }
            );
        }
        else {
            const jsonData = await req.json();
            const name = jsonData.name;
            const data = {message: `Hello there ${name}!`};
            return new Response(
                JSON.stringify(data),
                {
                    headers: {
                        "Content-Type": "application/json",
                        "Access-Control-Allow-Origin": "*",
                        "Access-Control-Allow-Methods": "POST",
                        "Access-Control-Expose-Headers": "Content-Length, X-JSON",
                        "Access-Control-Allow-Headers": "apikey,X-Client-Info, Content-Type, Authorization, Accept, Accept-Language, X-Authorization",
                    }
                }
            );
        }
});
```

**Comment by thorwebdev** [comment]
Thanks @GaryAustin1 I've replied on the other issue: https://github.com/supabase/supabase/issues/6267
