### ISSUE TITLE
`super` keyword type error

### ISSUE THREAD

**Issue by bombillazo** [supabase/functions-js#56]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When trying to compile our Next.js app which uses the supabase client, we are getting the following build/lint error:

```ts
./node_modules/@supabase/functions-js/src/types.ts:21:11
Type error: Only public and protected base class methods are accessible via the 'super' keyword.

  19 |   constructor(message: string, name = 'FunctionsError', context?: any) {
  20 |     super(message)
> 21 |     super.name = name
     |           ^
  22 |     this.context = context
  23 |   }
  24 | }
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. N/A

## Expected behavior

No type errors occur.

Im sure the fix is:

```ts
//replace 
super.name = name 

// with
this.name = name
```

## System information

- Version of supabase-js: 2.24.0

**Comment by soedirgo** [comment]
Merged the PR, thanks!
